name: trackit_mobile__frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  bloc: ^8.1.4
  fpdart: ^1.1.0
  intl: ^0.17.0
  go_router: ^14.1.4
  timeline_tile: ^2.0.0
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lazada.svg
    - assets/shopee.svg
    - assets/shopee-img.svg
    - assets/lazada-img.svg
